### ISSUE TITLE
switch case好像有点问题啊老哥

### ISSUE THREAD

**Issue by SealinGp** [dushixiang/4dnat#1]
```
switch args[1] {
	case "-listen":
	case "-l":
		listener(args[2], args[3])
		break
	}
```
这种写法好像不能达到或的效果啊,要改成这种,我这里试过了,不然你试试?
```
switch args[1] {
	case "-listen","-l":
		listener(args[2], args[3])
		break
	}
```

**Comment by limaofu** [comment]
默认只执行一个break，所以在写在一行中。

**Comment by limaofu** [comment]
还有，
①哥们写的这个forward不是dnat，它其实是端口代理，portProxy，即自己监听了某端口后，自己再做客户端向目标发起tcp连接。主机本身是要处理tcp的连接问题的。

②dnat是指直接修改tcp报文的目的ip或port，达到转发的目的，要求在主机上开启数据转发。即主机本身不处理tcp连接问题。

**Comment by dushixiang** [comment]
> ```
> switch args[1] {
> 	case "-listen":
> 	case "-l":
> 		listener(args[2], args[3])
> 		break
> 	}
> ```
> 
> 这种写法好像不能达到或的效果啊,要改成这种,我这里试过了,不然你试试?
> 
> ```
> switch args[1] {
> 	case "-listen","-l":
> 		listener(args[2], args[3])
> 		break
> 	}
> ```

我之前写Java的，习惯写俩case了，我改成go的风格吧。

**Comment by dushixiang** [comment]
> 还有，
> ①哥们写的这个forward不是dnat，它其实是端口代理，portProxy，即自己监听了某端口后，自己再做客户端向目标发起tcp连接。主机本身是要处理tcp的连接问题的。
> 
> ②dnat是指直接修改tcp报文的目的ip或port，达到转发的目的，要求在主机上开启数据转发。即主机本身不处理tcp连接问题。

是的，NAT属于网络层的技术，我这是工作在传输层转发Tcp报文的。
