### ISSUE TITLE
连接超时问题

### ISSUE THREAD

**Issue by limaofu** [dushixiang/4dnat#2]
连接超时怎么办，是一直net.dial建立连接吗？
端口转发时，其中一个端口的连接中断了，断开了。另一个怎么办，一直等吗，
如何主动检测连接中断，并关闭此线程呢

**Comment by dushixiang** [comment]
连接失败之后会等待5秒再次重连。
端口转发时我的设计就是即使一方断开了，另一方还保持连接，等待断开的一方重新连接，否则再次连接时另一方已经断开了，就无法打通连接了。
