### ISSUE TITLE
关于agent模式的一些问题

### ISSUE THREAD

**Issue by wenyurush** [dushixiang/4dnat#4]
在测试中发现使用 - -agent 时候 http的代理是正常的，socks5的代理做转发就存在问题。。是我个人原因么

我简单描述下

a 计算机  （我的操作计算机，可以上外网）  20.20.20.20
b 计算机 （内网计算机，不能外网，只能a  ssh过去）30.30.30.30

---
a 主机
1、 a  ssh tunnel b，起一个socks5代理  local 1122端口（因为我只能ssh 到b，b的其他端口全部无法访问，所以需要一个ssh隧道先）
2、起http代理 10800 (测试起socsk5代理存在问题)
3、然后 proxychains 4dnat agent  20.20.20.20:10800 30.30.30.30 10000

b 主机
1、4dnat  10000 10001
2、设置proxy

---

不知道是 4dnat的 agent问题，还是因为我先走了一层ssh  socks5代理的问题

**Comment by dushixiang** [comment]
> 在测试中发现使用 - -agent 时候 http的代理是正常的，socks5的代理做转发就存在问题。。是我个人原因么
> 
> 我简单描述下
> 
> a 计算机 （我的操作计算机，可以上外网） 20.20.20.20
> b 计算机 （内网计算机，不能外网，只能a ssh过去）30.30.30.30
> 
> a 主机
> 1、 a ssh tunnel b，起一个socks5代理 local 1122端口（因为我只能ssh 到b，b的其他端口全部无法访问，所以需要一个ssh隧道先）
> 2、起http代理 10800 (测试起socsk5代理存在问题)
> 3、然后 proxychains 4dnat agent 20.20.20.20:10800 30.30.30.30 10000
> 
> b 主机
> 1、4dnat 10000 10001
> 2、设置proxy
> 
> 不知道是 4dnat的 agent问题，还是因为我先走了一层ssh socks5代理的问题

4dnat 的 socks5代理比较简陋，如果你仅是想要 b计算机访问a上面启动的socks5代理，其实你可以用SSH隧道的远程转发功能，将本地计算机a监听的socks5端口映射到b计算机上，这样b就可以使用a上面的socks5代理了。

**Comment by wenyurush** [comment]
> > 在测试中发现使用 - -agent 时候 http的代理是正常的，socks5的代理做转发就存在问题。。是我个人原因么
> > 我简单描述下
> > a 计算机 （我的操作计算机，可以上外网） 20.20.20.20
> > b 计算机 （内网计算机，不能外网，只能a ssh过去）30.30.30.30
> > a 主机
> > 1、 a ssh tunnel b，起一个socks5代理 local 1122端口（因为我只能ssh 到b，b的其他端口全部无法访问，所以需要一个ssh隧道先）
> > 2、起http代理 10800 (测试起socsk5代理存在问题)
> > 3、然后 proxychains 4dnat agent 20.20.20.20:10800 30.30.30.30 10000
> > b 主机
> > 1、4dnat 10000 10001
> > 2、设置proxy
> > 不知道是 4dnat的 agent问题，还是因为我先走了一层ssh socks5代理的问题
> 
> 4dnat 的 socks5代理比较简陋，如果你仅是想要 b计算机访问a上面启动的socks5代理，其实你可以用SSH隧道的远程转发功能，将本地计算机a监听的socks5端口映射到b计算机上，这样b就可以使用a上面的socks5代理了。

一言点醒梦中人。。我把简单问题复杂化了。。。
